# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default (OnPrem)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '6.x'
  displayName: 'Install node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'Npm install and build'

- task: CopyFiles@2
  displayName: 'Stage Artifacts'
  inputs:
    SourceFolder: dist
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    ArtifactName: 'DenseAzDo'